sudo: required
services:
  - -docker

before_install:
  - docker build -t issamfellaki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true issamfellaki/react-test npm test

after_success:
  - docker build -t issamfellaki/multi-client ./client
  - docker build -t issamfellaki/multi-nginx  ./nginx
  - docker build -t issamfellaki/multi-server ./server
  - docker build -t issamfellaki/multi-worker ./worker
#Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push them to docker hub
  - docker push issamfellaki/multi-client
  - docker push issamfellaki/multi-nginx
  - docker push issamfellaki/multi-server
  - docker push issamfellaki/multi-worker
